=== kilicburak/EFSA/src/main/resources/utils/common/toc_01-04-00.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.oecd.org/TOCS" xmlns:cbc="http://www.oecd.org/GHSTS/CommonBasicComponent-1" targetNamespace="http://www.oecd.org/TOCS" elementFormDefault="qualified" attributeFormDefault="unqualified" version="01.04.00">
	<xs:include schemaLocation="ghsts-toc-picklists.xsd"/>
	<xs:import namespace="http://www.oecd.org/GHSTS/CommonBasicComponent-1" schemaLocation="./ghsts-CommonBasicComponents_01-04-00.xsd"/>
	<xs:element name="TOC">
		<xs:annotation>
			<xs:documentation>A dossier structure (Table of Content = TOC), which should be published</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TOC_SHORT_NAME" type="cbc:string20">
					<xs:annotation>
						<xs:documentation>Wordwide unique short name to identify this TOC </xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="TOC_PID" type="cbc:PIDType">
					<xs:annotation>
						<xs:documentation>Wordwide unique identifier of the Table of Contents</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="TOC_OWNER">
					<xs:annotation>
						<xs:documentation>The owner has the responsibility for this ToC</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="VALUE" type="EXTENSION_TYPE_TOC_OWNER">
								<xs:annotation>
									<xs:documentation>Code according restricted picklist TYPE_TOC_OWNER; other values are submitted via attribute 'Other_Value'</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="VALUE_DECODE" type="cbc:string255">
								<xs:annotation>
									<xs:documentation>Long text of 'Value' or 'Other_Value'</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="TOC_FULL_NAME" type="cbc:string255">
					<xs:annotation>
						<xs:documentation>Full Name for the TOC (Dossier-Structure)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="TOC_VERSION" type="cbc:versionnumberType">
					<xs:annotation>
						<xs:documentation>TOC Version</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="TO_USE_FROM" type="xs:date">
					<xs:annotation>
						<xs:documentation>This TOC is valid from ...(default= publishing date)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="TO_USE_UNTIL" type="xs:date" minOccurs="0">
					<xs:annotation>
						<xs:documentation>This TOC was valid until ...</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="STRUCTURE">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="TOC_NODE" type="TYPE_TOC_NODE"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TOC_NODE" type="TYPE_TOC_NODE">
		<xs:annotation>
			<xs:documentation>TOC-Nodes (Annex Points) in sequence of their usage in the Dossier</xs:documentation>
		</xs:annotation>
		<xs:key name="TocNodePID">
			<xs:selector xpath="."/>
			<xs:field xpath="TOC_NODE_PID"/>
		</xs:key>
	</xs:element>
	<xs:complexType name="TYPE_TOC_NODE">
		<xs:annotation>
			<xs:documentation>A ToC has a lot of TOC-Nodes, identified by unique TOC NODE NAME and PID</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="NODE_NAME" type="cbc:string20">
				<xs:annotation>
					<xs:documentation>Unique String inside of the ToC</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="NODE_HEADING" type="cbc:string255">
				<xs:annotation>
					<xs:documentation>Heading text </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DOCUMENT_REFERENCES" type="xs:boolean"/>
			<xs:element name="LOGICAL_DELETED" type="xs:boolean"/>
			<xs:element name="TOC_NODE_PID" type="cbc:PIDType">
				<xs:annotation>
					<xs:documentation>World wide unique identifier for TOC Nodes. This PID should be the basis for cross references between different TOC's </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TOC_NODE" type="TYPE_TOC_NODE" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== kilicburak/EFSA/target/classes/utils/toc/TOC_EFSA_FEED_2016_01.00.00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by GHSTS ToC Maintenance XLS on 23-Jun-2014 11:40:28 AM -->
<TOC xmlns="http://www.oecd.org/TOCS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.oecd.org/TOCS ../common/toc_01-04-00.xsd">
	<TOC_SHORT_NAME>EFSA FEED 2016</TOC_SHORT_NAME>
	<TOC_PID>urn:com:efsa:feed:3f41657a-435d-48be-bce2-a27f5c6040ea</TOC_PID>
	<TOC_OWNER>
		<VALUE>other</VALUE>
		<VALUE_DECODE>EFSA</VALUE_DECODE>
	</TOC_OWNER>
	<TOC_FULL_NAME>Table of Content for FEED according to the EFSA guidance on the submission of applications for authorisation of Feed</TOC_FULL_NAME>
	<TOC_VERSION>01.00.00</TOC_VERSION>
	<TO_USE_FROM>2017-01-01</TO_USE_FROM>
	<STRUCTURE>
		<TOC_NODE>
			<NODE_NAME>Section I</NODE_NAME>
			<NODE_HEADING>Summary of the dossier</NODE_HEADING>
			<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
			<LOGICAL_DELETED>false</LOGICAL_DELETED>
			<TOC_NODE_PID>urn:com:efsa:feed:cd1a3a5c-213d-4644-af30-2edf49904a79</TOC_NODE_PID>
			<TOC_NODE>
				<NODE_NAME>1.1</NODE_NAME>
				<NODE_HEADING>Public Summary</NODE_HEADING>
				<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:07d2b6bd-310e-4207-9d99-ac641d4af64a</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>1.2</NODE_NAME>
				<NODE_HEADING>Scientific Summary</NODE_HEADING>
				<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:391ae8c1-a05a-407a-84c4-795c3b3398ba</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>1.3</NODE_NAME>
				<NODE_HEADING>List of documents and other particulars</NODE_HEADING>
				<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:59f1969b-5348-48ab-af45-609008cb8d6d</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>1.4</NODE_NAME>
				<NODE_HEADING>List of parts of the dossier requested to be treated as confidential</NODE_HEADING>
				<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:1a4170fb-e37d-432f-9eb7-5e8de4c0298d</TOC_NODE_PID>
			</TOC_NODE>
		</TOC_NODE>
		<TOC_NODE>
			<NODE_NAME>Section II</NODE_NAME>
			<NODE_HEADING>Identity, Characterisation and condition of use of the additive</NODE_HEADING>
			<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
			<LOGICAL_DELETED>false</LOGICAL_DELETED>
			<TOC_NODE_PID>urn:com:efsa:feed:6e2b700a-d020-4105-8d35-90b4bf12c1ca</TOC_NODE_PID>
			<TOC_NODE>
				<NODE_NAME>2.1</NODE_NAME>
				<NODE_HEADING>Identity of the additive</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:573f4015-71ce-4263-9e7f-895878d6db87</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>2.2</NODE_NAME>
				<NODE_HEADING>Characterisation of the active substance(s)/agent(s)</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:0f10eb36-a379-41ef-ad8d-0a70a68a8f82</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>2.3</NODE_NAME>
				<NODE_HEADING>Manufacturing process</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:729cc8e1-823b-49be-8d3b-fda3d5c8b7fe</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>2.4</NODE_NAME>
				<NODE_HEADING>Technological properties</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:bec6d5b1-a56f-429d-b207-db8857026e9d</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>2.5</NODE_NAME>
				<NODE_HEADING>Conditions of use</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:638001fc-9d15-4367-991c-60fe2ef75a6c</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>2.6</NODE_NAME>
				<NODE_HEADING>Methods of analysis and reference samples</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:9d567d24-9f9d-40cc-9fbd-3e2bc574d470</TOC_NODE_PID>
			</TOC_NODE>
		</TOC_NODE>
		<TOC_NODE>
			<NODE_NAME>Section III</NODE_NAME>
			<NODE_HEADING>Safety of the additive</NODE_HEADING>
			<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
			<LOGICAL_DELETED>false</LOGICAL_DELETED>
			<TOC_NODE_PID>urn:com:efsa:feed:9436bf0d-db6a-4488-962a-ff51e491f84a</TOC_NODE_PID>
			<TOC_NODE>
				<NODE_NAME>3.1</NODE_NAME>
				<NODE_HEADING>Safety for the target species</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:693bf32d-82e3-4f88-9d71-70b2cfcf4b44</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>3.2</NODE_NAME>
				<NODE_HEADING>Safety for the consumer</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:90d0e6ec-0a4f-4503-9496-45eef8aa1ef2</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>3.3</NODE_NAME>
				<NODE_HEADING>Safety for the user</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:5055fffe-d191-4d61-8dbe-97e487f59ff6</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>3.4</NODE_NAME>
				<NODE_HEADING>Safety for the environment</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:d7678b5c-c37a-485c-82e0-d557be227290</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>Section IV</NODE_NAME>
				<NODE_HEADING>Efficacy</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:15c7d6ad-0fda-4f83-b962-42cefc62d5e1</TOC_NODE_PID>
				<TOC_NODE>
					<NODE_NAME>4.1</NODE_NAME>
					<NODE_HEADING>In vitro studies</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:4bf5d45a-c0c1-4c53-ba82-ba7ac9ef34bf</TOC_NODE_PID>
				</TOC_NODE>
				<TOC_NODE>
					<NODE_NAME>4.2</NODE_NAME>
					<NODE_HEADING>Short term efficacy studies with animals</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:5bbe00a1-9d1b-4e8f-9d44-65183f05cdbf</TOC_NODE_PID>
				</TOC_NODE>
				<TOC_NODE>
					<NODE_NAME>4.3</NODE_NAME>
					<NODE_HEADING>Long term efficacy studies with animals</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:42b5a064-0003-47e0-8aca-d24e512136c9</TOC_NODE_PID>
				</TOC_NODE>
				<TOC_NODE>
					<NODE_NAME>4.4</NODE_NAME>
					<NODE_HEADING>Duration of long term efficacy studies with target animals</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:3ba1b1ba-c71e-4759-a79a-437a65319ee1</TOC_NODE_PID>
				</TOC_NODE>
				<TOC_NODE>
					<NODE_NAME>4.5</NODE_NAME>
					<NODE_HEADING>Efficacy requirements for additive categories and functional groups</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:e20e7b7f-e03a-4702-8138-e37f39552326</TOC_NODE_PID>
				</TOC_NODE>
				<TOC_NODE>
					<NODE_NAME>4.6</NODE_NAME>
					<NODE_HEADING>Studies on the quality of animal products where this is not the effect claimed</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:13d13039-4c17-4258-9bcd-5d9313716d27</TOC_NODE_PID>
				</TOC_NODE>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>Section V</NODE_NAME>
				<NODE_HEADING>Post Market Monitoring Plan</NODE_HEADING>
				<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:2dd2b4ec-0086-46d4-b028-aea22bba0623</TOC_NODE_PID>
			</TOC_NODE>
			<TOC_NODE>
				<NODE_NAME>ADM</NODE_NAME>
				<NODE_HEADING>Administrative document</NODE_HEADING>
				<DOCUMENT_REFERENCES>false</DOCUMENT_REFERENCES>
				<LOGICAL_DELETED>false</LOGICAL_DELETED>
				<TOC_NODE_PID>urn:com:efsa:feed:1a847d97-d6b3-4e90-bf06-74202a643d0c</TOC_NODE_PID>
				<TOC_NODE>
					<NODE_NAME>ADM-1</NODE_NAME>
					<NODE_HEADING>Cover letter</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:ca43dffa-ed5e-420a-932b-c051ddc5f9d6</TOC_NODE_PID>
				</TOC_NODE>
				<TOC_NODE>
					<NODE_NAME>ADM-2</NODE_NAME>
					<NODE_HEADING>Copy of the application form in accordance with Annex I of Regulation (EC) No 429/2008</NODE_HEADING>
					<DOCUMENT_REFERENCES>true</DOCUMENT_REFERENCES>
					<LOGICAL_DELETED>false</LOGICAL_DELETED>
					<TOC_NODE_PID>urn:com:efsa:feed:f326f7fc-ab75-4c07-9f19-d06939b29312</TOC_NODE_PID>
				</TOC_NODE>
			</TOC_NODE>
		</TOC_NODE>
	</STRUCTURE>
</TOC>
